# use production url as much as you can.
host: "0.0.0.0"
port: 44497
user: "" # you should replace it with your username
argo_url: "https://apps-dev.inside.anl.gov/argoapi/api/v1/resource/chat/"
argo_stream_url: "https://apps-dev.inside.anl.gov/argoapi/api/v1/resource/streamchat/"
argo_embedding_url: "https://apps.inside.anl.gov/argoapi/api/v1/resource/embed/"
verbose: true
num_workers: 5
timeout: 600 # in seconds
